### ISSUE TITLE
Update leaflet-providers for continued access to Stamen map tiles

### ISSUE THREAD

**Issue by kent37** [rstudio/leaflet.providers#25]
Quoting from https://github.com/leaflet-extras/leaflet-providers/issues/519:

> Stamen will tiles will be migrated to Stadia on october 31 ref :
> 
> > Stadia Maps has [partnered with Stamen Design](http://maps.stamen.com/stadia-partnership/) to host their iconic map styles. If you are currently accessing Stamen map tiles via the Fastly CDN or a Stamen domain, you'll need to make a few (small!) changes to keep on using these maps after August 31, 2023. After this point, we will start progressive brownouts before the old URLs stop working entirely on October 31, 2023.
> 
> https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/
> https://stamen.com/here-comes-the-future-of-stamen-maps/

`leaflet-providers` has been updated to use the new Stadia URLs. For Stamen tiles to continue to work with `{leaflet}`, the new `leaflet-providers` is needed.

**Comment by ianthetechie** [comment]
Hello everyone,

Ian from Stadia Maps here! I'm just making the rounds of libraries with decent traffic and came across this issue. Just a heads-up that the PR to address this in leaflet-providers upstream (https://github.com/leaflet-extras/leaflet-providers/pull/520) was opened a few weeks ago but just merged recently. I can't speak for the maintainers of that package, but it sounds like the 2.0.0 release will probably go out to npm later this week.

As with the similar OpenLayers PR, it's a breaking change (instead of provider names like `Stamen.Toner`, they will now be `Stadia.StamenToner`, since we're hosting the tiles but are still branded + contain attribution to Stamen), hence the major semver bump. I'm not sure what that means for your API, but just thought I'd drop in to flag that in case you need to do something similar. Feel free to tag me if you have any questions!

**Comment by ianthetechie** [comment]
Looks like the 2.0.0 release is out now on npm.
